
networks:
  argentina: 

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    networks:
      - argentina
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: botuser
      POSTGRES_PASSWORD: Argentina010225
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  bot:
    build: .
    container_name: bot
    restart: always
    networks:
      - argentina
    depends_on:
      - postgres
    environment:
      DB_URL: "postgresql+asyncpg://botuser:Argentina010225@localhost:5433/agregator"
    volumes:
      - .:/bot
    working_dir: /bot
    command: ["python", "bot/bot.py"]

volumes:
  postgres_data: